version: '2.1'
services:
  php:
    container_name: dockerized_lara_php
    build: ./docker/php
    working_dir: /var/www
    volumes:
      - ./app/:/var/www/
      - ./docker/files/dockeried_lara.ini:/usr/local/etc/php/conf.d/dockeried_lara.ini
    links:
      - mongo
      - mysql
      - redis
################NGINX################
  nginx:
    container_name: dockerized_lara_nginx
    build: ./docker/nginx
    working_dir: /etc/nginx/conf.d/
    ports:
      - "8001:80"
    volumes:
      - ./docker/files/nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php

 ################MONGODB################
  mongo:
    container_name: dockerized_lara_mongo
    build: ./docker/mongo
    ports:
      - 57017:27017
    volumes:
      - ./app/storage/mongodb:/data/db
################REDIS################
  redis:
    build: ./docker/redis
    container_name: dockerized_lara_redis
    ports:
      - "5379:6379"
################MYSQL################
#https://hub.docker.com/_/mariadb/
  mysql:
    image: mariadb:latest
    container_name: dockerized_lara_mysql
    volumes:
      - ./app/storage/mysql:/var/lib/mysql
    ports:
      - "5306:3306"
    restart: always
    environment:
        MYSQL_USER: lara_user
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: dockerized_lara
        MYSQL_PASSWORD: root
